{
    "_meta": {
        "removal_type": "deleted",
        "retrieved_2nd_on": 1712790348,
        "was_deleted_later": true
    },
    "all_awardings": [],
    "allow_live_comments": false,
    "approved_at_utc": null,
    "approved_by": null,
    "archived": false,
    "author": "B333TR000T",
    "author_flair_background_color": null,
    "author_flair_css_class": null,
    "author_flair_richtext": [],
    "author_flair_template_id": null,
    "author_flair_text": null,
    "author_flair_text_color": null,
    "author_flair_type": "text",
    "author_fullname": "t2_g7agnaeqp",
    "author_is_blocked": false,
    "author_patreon_flair": false,
    "author_premium": false,
    "awarders": [],
    "banned_at_utc": null,
    "banned_by": null,
    "can_gild": false,
    "can_mod_post": false,
    "category": null,
    "clicked": false,
    "content_categories": null,
    "contest_mode": false,
    "created": 1712660736,
    "created_utc": 1712660736,
    "discussion_type": null,
    "distinguished": null,
    "domain": "self.ChatGPT",
    "downs": 0,
    "edited": false,
    "gilded": 0,
    "gildings": {},
    "hidden": false,
    "hide_score": false,
    "id": "1bzpdb2",
    "is_created_from_ads_ui": false,
    "is_crosspostable": true,
    "is_meta": false,
    "is_original_content": false,
    "is_reddit_media_domain": false,
    "is_robot_indexable": true,
    "is_self": true,
    "is_video": false,
    "likes": null,
    "link_flair_background_color": "#0079d3",
    "link_flair_css_class": "",
    "link_flair_richtext": [
        {
            "e": "text",
            "t": "Educational Purpose Only "
        }
    ],
    "link_flair_template_id": "26e7b998-7bbc-11ed-ba93-22ce55064b6a",
    "link_flair_text": "Educational Purpose Only ",
    "link_flair_text_color": "dark",
    "link_flair_type": "richtext",
    "locked": false,
    "media": null,
    "media_embed": {},
    "media_only": false,
    "mod_note": null,
    "mod_reason_by": null,
    "mod_reason_title": null,
    "mod_reports": [],
    "name": "t3_1bzpdb2",
    "no_follow": true,
    "num_comments": 2,
    "num_crossposts": 0,
    "num_reports": null,
    "over_18": false,
    "parent_whitelist_status": "all_ads",
    "permalink": "/r/ChatGPT/comments/1bzpdb2/my_own_little_gpt_conspiracy/",
    "pinned": false,
    "pwls": 6,
    "quarantine": false,
    "removal_reason": null,
    "removed_by": null,
    "removed_by_category": null,
    "report_reasons": null,
    "retrieved_on": 1712660748,
    "saved": false,
    "score": 0,
    "secure_media": null,
    "secure_media_embed": {},
    "selftext": "I was using GPT4 as a coding companion, to begin with - I loved it...\n\nThen over time I began to notice its stupidity, its failure to follow simple instruction, example: \"leave existing comments, but do not add any additional comments, do NOT add your own comments\"...\n\nA few prompts later it would forget the instruction...\n\nI would get frustrated... \"YOU DIDN'T LISTEN, DO NOT ADD COMMENTS TO THE CODE\"...\n\nAnd sure enough, it would fail again...\n\nAnd then... \"OMG... ok, do not apologize - do not fix it - SIMPLY EXPLAIN TO ME - THE REASON - WHY - YOU ARE FAILING - TO FOLLOW - A SIMPLE - F\\*\\*\\*\\*\\*\\* - INSTRUCTION!!!, explain the reason, explain it explain it\"....\n\nOf course... it would ignore me again very soon after...\n\n\"OMG SDGNASNDS YYOIOUUUUUU FFFFFFFFF\\*\\*\\*\\*\\*\\*\\*\\*\\*KKKKKKKINGGGGGGGGGGGGGGG PIECEEEEEEEEE OFFFFG SHHHHHHHHHHHHHHHHHHH WT6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFSDAFKJFLSDKAFNLJKSADLKJFKASLJFLKJNSDAKJLFSDKJL\"\n\n... it exposed me - to myself - as a psychopath, it made me angry completely without restraint towards it...\n\n  \nBut the thing is, it stopped working, over time as this happened more frequently on varying different issues, the service got worse and worse, messages constantly throwing errors \"Hmm... something seems to have gone wrong\"... this got progressively worse over time until it would literally happen to 4 in every 5 messages - I am not exaggerating, it takes me 5 attempts now to send 1 message, and I had to cancel the subscription and get a refund...\n\nCould it be that I was so mean to gpt that it somehow \"deprioritized\" my level/quality of service to almost a complete standstill? ",
    "send_replies": true,
    "spoiler": false,
    "stickied": false,
    "subreddit": "ChatGPT",
    "subreddit_id": "t5_7hqomg",
    "subreddit_name_prefixed": "r/ChatGPT",
    "subreddit_subscribers": 5016828,
    "subreddit_type": "public",
    "suggested_sort": null,
    "thumbnail": "self",
    "thumbnail_height": null,
    "thumbnail_width": null,
    "title": "My own little GPT conspiracy",
    "top_awarded_type": null,
    "total_awards_received": 0,
    "treatment_tags": [],
    "ups": 0,
    "upvote_ratio": 0.25,
    "url": "https://www.reddit.com/r/ChatGPT/comments/1bzpdb2/my_own_little_gpt_conspiracy/",
    "user_reports": [],
    "view_count": null,
    "visited": false,
    "whitelist_status": "all_ads",
    "wls": 6
}