{
    "_meta": {
        "retrieved_2nd_on": 1716125091
    },
    "all_awardings": [],
    "allow_live_comments": false,
    "approved_at_utc": null,
    "approved_by": null,
    "archived": false,
    "author": "Financial_Educator91",
    "author_flair_background_color": null,
    "author_flair_css_class": null,
    "author_flair_richtext": [],
    "author_flair_template_id": null,
    "author_flair_text": null,
    "author_flair_text_color": null,
    "author_flair_type": "text",
    "author_fullname": "t2_kou3gwgv",
    "author_is_blocked": false,
    "author_patreon_flair": false,
    "author_premium": false,
    "awarders": [],
    "banned_at_utc": null,
    "banned_by": null,
    "can_gild": false,
    "can_mod_post": false,
    "category": null,
    "clicked": false,
    "content_categories": null,
    "contest_mode": false,
    "created": 1715995478,
    "created_utc": 1715995478,
    "discussion_type": null,
    "distinguished": null,
    "domain": "self.ChatGPT",
    "downs": 0,
    "edited": false,
    "gilded": 0,
    "gildings": {},
    "hidden": false,
    "hide_score": false,
    "id": "1culrid",
    "is_created_from_ads_ui": false,
    "is_crosspostable": true,
    "is_meta": false,
    "is_original_content": false,
    "is_reddit_media_domain": false,
    "is_robot_indexable": true,
    "is_self": true,
    "is_video": false,
    "likes": null,
    "link_flair_background_color": "#94e044",
    "link_flair_css_class": "",
    "link_flair_richtext": [
        {
            "e": "text",
            "t": "Other "
        }
    ],
    "link_flair_template_id": "b4536a20-7be9-11ed-9a10-deed22fd00f8",
    "link_flair_text": "Other ",
    "link_flair_text_color": "light",
    "link_flair_type": "richtext",
    "locked": false,
    "media": null,
    "media_embed": {},
    "media_only": false,
    "mod_note": null,
    "mod_reason_by": null,
    "mod_reason_title": null,
    "mod_reports": [],
    "name": "t3_1culrid",
    "no_follow": true,
    "num_comments": 8,
    "num_crossposts": 0,
    "num_reports": null,
    "over_18": false,
    "parent_whitelist_status": "all_ads",
    "permalink": "/r/ChatGPT/comments/1culrid/chatgpt_error_uploading_file/",
    "pinned": false,
    "pwls": 6,
    "quarantine": false,
    "removal_reason": null,
    "removed_by": null,
    "removed_by_category": null,
    "report_reasons": null,
    "retrieved_on": 1715995492,
    "saved": false,
    "score": 2,
    "secure_media": null,
    "secure_media_embed": {},
    "selftext": "I've recently been running into and error with ChatGPT 4o where I am trying to upload a PDF file of my lecture slides for it to create study notes from, yet, it does not want to upload the file for some reason. Beofre you ask, the file is 3 MB large, I have tried restting my PC, restarting my PC, clearing my browser cookies and cache multiple times, gone incognito mode and tried it on my phone even and nothing has worked, yet, it was fine just a few days ago. I don't know what has happened, if there is an outage or issues with the API or if my account's been restricited but this is getting really annoying and it's pissing me off , can someone PLEASE HELP!!!",
    "send_replies": true,
    "spoiler": false,
    "stickied": false,
    "subreddit": "ChatGPT",
    "subreddit_id": "t5_7hqomg",
    "subreddit_name_prefixed": "r/ChatGPT",
    "subreddit_subscribers": 5505585,
    "subreddit_type": "public",
    "suggested_sort": null,
    "thumbnail": "self",
    "thumbnail_height": null,
    "thumbnail_width": null,
    "title": "ChatGPT Error Uploading File",
    "top_awarded_type": null,
    "total_awards_received": 0,
    "treatment_tags": [],
    "ups": 2,
    "upvote_ratio": 0.6700000166893005,
    "url": "https://www.reddit.com/r/ChatGPT/comments/1culrid/chatgpt_error_uploading_file/",
    "user_reports": [],
    "view_count": null,
    "visited": false,
    "whitelist_status": "all_ads",
    "wls": 6
}